name: simplechat
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  http: ^0.13.1
  shared_preferences: ^2.0.3
  image_picker: ^0.7.2
  device_info: ^2.0.0
  flutter_svg: ^0.19.3
  contacts_service: ^0.4.6
  permission_handler: ^5.1.0+2
  dotted_border: ^1.0.7
  video_player: ^2.0.2
  path_provider: ^2.0.1
  page_view_indicators: ^2.0.0
  percent_indicator: ^2.1.9+1

  socket_io_client: ^0.9.4
  flutter_simple_dependency_injection: ^1.0.1
  flutter_local_notifications: ^4.0.1+2

  intl: ^0.17.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true

  assets:
   - assets/images/
   - assets/icons/
   - assets/fonts/
   - assets/fonts/montserrat_thin.ttf
   - assets/fonts/montserrat_light.ttf
   - assets/fonts/montserrat_regular.ttf
   - assets/fonts/montserrat_medium.ttf
   - assets/fonts/montserrat_semiBold.ttf
   - assets/fonts/montserrat_bold.ttf
   - assets/fonts/montserrat_extraBold.ttf
   - assets/fonts/montserrat_black.ttf

  fonts:
   - family: Montserrat
     fonts:
       - asset: assets/fonts/montserrat_thin.ttf
         weight: 100
       - asset: assets/fonts/montserrat_light.ttf
         weight: 200
       - asset: assets/fonts/montserrat_regular.ttf
         weight: 300
       - asset: assets/fonts/montserrat_medium.ttf
         weight: 400
       - asset: assets/fonts/montserrat_semiBold.ttf
         weight: 500
       - asset: assets/fonts/montserrat_bold.ttf
         weight: 600
       - asset: assets/fonts/montserrat_extraBold.ttf
         weight: 700
       - asset: assets/fonts/montserrat_black.ttf
         weight: 800

flutter_intl:
  main_locale: en_US
  enabled: true
